# Generated by Django 4.2.15 on 2024-09-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_postmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='title',
            field=models.CharField(error_messages={'unique': 'This title is not unique, please try again'}, max_length=120, null=True, unique=True),
        ),
    ]
