# Generated by Django 4.2.15 on 2024-09-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_postmodel_timestamp_postmodel_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active Status'),
        ),
    ]
