# Generated by Django 5.1 on 2024-08-29 09:39

import home.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_passenger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(home.models.set_delete_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
